### ISSUE TITLE
"Your extension doesn't have an array of files in it" error when recompiling C# extension for IDE 2024.2.0.132

### ISSUE THREAD

**Issue by ghost** [YAL-GameMaker-Tools/GmxGen#1]
When I build my extension while it's .yy is still in an older asset format, it compiles as normal.

As I import the extension asset into GameMaker, GameMaker converts both the original .yy asset in my extension solution folder, and the imported copy, to the newest format for 2024.2.0.132. 

When I go to build it again in Visual Studio, I get the following build error: "Your extension doesn't have an array of files in it."
This is probably being caused by the new IDE version changing how the .yy file is formatted. I've attached a screenshot of the error below

![image](https://github.com/YAL-GameMaker-Tools/GmxGen/assets/57552959/59cf7567-4df2-4b2c-8aef-bc114d61a71d)

**Comment by YellowAfterlife** [comment]
Fixed [in the new release](https://github.com/YAL-GameMaker-Tools/GmxGen/releases/tag/2024-03-22)
